### ISSUE TITLE
ImportError: cannot import name 'Repo'

### ISSUE THREAD

**Issue by thoean** [Cimpress-MCP/JustReleaseNotes#58]
I'm getting the following error after upgrading GitPython from 2.0.9 to 2.1.0:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/JustReleaseNotes/factory.py", line 6, in createWithConfig
    module = importlib.import_module(module + ".{0}".format(name))
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/local/lib/python3.4/dist-packages/JustReleaseNotes/sourcers/GitRepo.py", line 2, in <module>
    from git import Repo
ImportError: cannot import name 'Repo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/just_release", line 9, in <module>
    load_entry_point('JustReleaseNotes==0.1.12', 'console_scripts', 'just_release')()
  File "/usr/local/lib/python3.4/dist-packages/JustReleaseNotes/command_line.py", line 27, in main
    generate_release_notes(args.config)
  File "/usr/local/lib/python3.4/dist-packages/JustReleaseNotes/command_line.py", line 81, in generate_release_notes
    repo = JustReleaseNotes.sourcers.factory.create(conf["Source"])
  File "/usr/local/lib/python3.4/dist-packages/JustReleaseNotes/sourcers/factory.py", line 5, in create
    return JustReleaseNotes.factory.createWithConfig("JustReleaseNotes.sourcers", conf["Provider"], conf)
  File "/usr/local/lib/python3.4/dist-packages/JustReleaseNotes/factory.py", line 11, in createWithConfig
    raise Exception("Unable to create module provider {0} from module {1}: {2}".format(conf["Provider"], module, e))
Exception: Unable to create module provider GitRepo from module JustReleaseNotes.sourcers: cannot import name 'Repo'
```

The same thing happens when I run a simple command line:

```
/usr/bin/python3.4 -c "from git import Repo" && echo "ok"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'Repo'
```
